# Generated by Django 5.0.7 on 2025-01-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuariopersonalizado_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='username',
        ),
    ]
