# Generated by Django 5.0.7 on 2025-01-24 17:52

import cpf_field.models
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuariopersonalizado_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', usuarios.models.CPFField(max_length=14, verbose_name='CPF')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='cpf',
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='CPF',
            field=cpf_field.models.CPFField(default=11111111111, max_length=14, verbose_name='cpf'),
            preserve_default=False,
        ),
    ]
