# Generated by Django 5.0.7 on 2025-01-31 22:02

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_mymodel_remove_usuariopersonalizado_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='CPF',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='CPF'),
        ),
    ]
