# Generated by Django 5.0.7 on 2024-11-27 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_usuarios_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Endereço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('CEP', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('id_Carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.carrinho')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='preço unitario')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pagamento', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='total')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='preço')),
                ('estoque', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='imagens')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('foto_perfi', models.ImageField(upload_to='imagens')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='id_Pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pedido'),
        ),
        migrations.AddField(
            model_name='item_pedido',
            name='id_Pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pedido'),
        ),
        migrations.AddField(
            model_name='item_pedido',
            name='id_Produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.produto'),
        ),
        migrations.AddField(
            model_name='item_carrinho',
            name='id_Produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.produto'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='id_Produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.usuario'),
        ),
        migrations.AddField(
            model_name='endereço',
            name='id_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.usuario'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='id_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.usuario'),
        ),
    ]
